# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cbd9cae86d58f1417e6c8d49f6205c14b02067d3a57af825ac286d5f875f176455fc66bbca7d7c90a4a435ac32ec99079eb7a8f1aa98b0140564525747402d29

test:
  secret_key_base: 7d5e537f2f4e5ed90ab1cf6382f24157f6615112140625245ca0338ddb04c03f97600170ba7e4aa553fee66841719b76dc9c7936ba2a4d588a7745c4d55caf33

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
